### ISSUE TITLE
Обнуляется время в методе installGame при добавлении одной и той же игры

### ISSUE THREAD

**Issue by VictoriaTatarinova** [OlegFilippoff/teamTask#1]
### Описание
При добавлении одной и той же игры в методе installGame обнуляется время.

### Локация дефекта
https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/main/java/ru/netology/Player.java#L25

###  Шаги воспроизведения
1. Открыть [код программы](https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/main/java/ru/netology/Player.java) в IDEA.
2. Запустить [тест](https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/test/java/ru/netology/PlayerTest.java#L116)

Ожидаемый результат: На консоли выводится 1.
Фактический результат: На консоли выводится 0.

### Скриншот
<img width="1249" alt="Снимок экрана 2022-07-16 в 21 10 14" src="https://user-images.githubusercontent.com/103593418/179368894-7753c84e-a4fe-4564-8b39-f75a1ff846c3.png">

### Окружение
* Операционная система: macOS Monterey 12.3.1
* IDE: IntelliJ IDEA 2022.1.1 (Community Edition)
* Java: OpenJDK 11

**Comment by OlegFilippoff** [comment]
![image](https://user-images.githubusercontent.com/94902304/179731723-8d5fc18e-8fc6-4d92-ac08-9e6465e81c57.png)
fixed #1
