### ISSUE TITLE
В методе addPlayTime нет проверки ввода отрицательных значений

### ISSUE THREAD

**Issue by OlegFilippoff** [OlegFilippoff/teamTask#10]
**Описание**
Метод addPlayTime не проверят ввод отрицательных значений времени и принимает такие значения

**Локация дефекта**
https://github.com/OlegFilippoff/teamTask/blob/8be551402fd790a5fe22daa46349e8989e50e42d/src/main/java/ru/netology/GameStore.java#L46-L52
**Шаги воспроизведения**

1. Открыть [код программы](https://github.com/OlegFilippoff/teamTask/blob/092eed6c73d0c1482953a4444cbd3a04ddace121/src/main/java/ru/netology/GameStore.java#L46-L52) в IDEA.

1. Запустить [тест](https://github.com/OlegFilippoff/teamTask/blob/71c815ca1d0d8dae239f95de90bb4b95d35fefd1/src/test/java/ru/netology/GameStoreTest.java#L175-L179) shouldAddPlayTimeLessThenZero

Ожидаемый результат: Программа возвращает RuntimeExection
Фактический результат: Отрицательные значения меньше нуля (включительно) валидируются.

**Скриншот**
![runtimeExectionZERO](https://user-images.githubusercontent.com/94902304/179421199-96104c3a-10ef-4557-8b9f-374380051dc2.png)

**Окружение**
Операционная система: Windows 10 homeEditon
IDE: IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2034M
Cores: 8
Non-Bundled Plugins:
    com.javarush.plugin2 (3.57)
    Key Promoter X (2022.2)
Kotlin: 221-1.6.20-release-285-IJ5080.210
Java: OpenJDK 11

**Comment by VictoriaTatarinova** [comment]
![image](https://user-images.githubusercontent.com/103593418/179738140-21ed5701-c146-4bb2-81b0-314eba359c2f.png)

fixed issue#10
