### ISSUE TITLE
Метод getMostPlayer возвращает только одного игрока, не предусмотрена ситуация с равным код-вом наигранного времени

### ISSUE THREAD

**Issue by OlegFilippoff** [OlegFilippoff/teamTask#11]
**Описание**
В методе нужно переписать логику так, чтобы в случае, если несколько игроков имеют одинаковое кол-во наигранных часов, метод возвращал массив этих игроков, а не одного, как сейчас. 

**Локация дефекта**
https://github.com/OlegFilippoff/teamTask/blob/8e4ea6fbe7404006f1986a2690c1a503838423db/src/main/java/ru/netology/GameStore.java#L58-L70
**Шаги воспроизведения**

1. Открыть [код программы](https://github.com/OlegFilippoff/teamTask/blob/gamestore/src/main/java/ru/netology/GameStore.java) в IDEA.

1. Запустить [тест](https://github.com/OlegFilippoff/teamTask/blob/8e4ea6fbe7404006f1986a2690c1a503838423db/src/test/java/ru/netology/GameStoreTest.java#L158) shouldCompareEqualPlayedTime

Ожидаемый результат: Возвращает значение "{"Aaron", "Bob"}"
Фактический результат: Возвращает ошибку типа org.opentest4j.AssertionFailedError: array lengths differ

**Скриншот**
![compareEqualTime](https://user-images.githubusercontent.com/94902304/179479542-9e1197ab-2c74-4e16-967e-3b85f696b826.png)

**Окружение**
Операционная система: Windows 10 homeEditon
IDE: IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2034M
Cores: 8
Non-Bundled Plugins:
    com.javarush.plugin2 (3.57)
    Key Promoter X (2022.2)
Kotlin: 221-1.6.20-release-285-IJ5080.210
Java: OpenJDK 11

**Comment by VictoriaTatarinova** [comment]
![image](https://user-images.githubusercontent.com/103593418/179738289-23766990-8afa-440d-92d6-9423d8aebb40.png)

fixed issue#11
