### ISSUE TITLE
Не выдается ошибка в методе play, если игра не была установлена

### ISSUE THREAD

**Issue by VictoriaTatarinova** [OlegFilippoff/teamTask#2]
### Описание
Метод  *public int play(Game game, int hours)* не выдает ошибку *RuntimeException*, если игра не была установлена.

### Локация дефекта
https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/main/java/ru/netology/Player.java#L33-L41

### Шаги воспроизведения
1. Открыть [код программы](https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/main/java/ru/netology/Player.java) в IDEA.
2. Запустить [тест](https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/test/java/ru/netology/PlayerTest.java#L46).

*Ожидаемый результат*: На консоли выводится *RuntimeException*.
*Фактический результат*: На консоли выводится *org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.*

### Скриншот
<img width="1249" alt="Снимок экрана 2022-07-16 в 21 57 03" src="https://user-images.githubusercontent.com/103593418/179370250-408499f6-309e-4db8-ac5b-65439dbbdd2d.png">

### Окружение
* Операционная система: macOS Monterey 12.3.1
* IDE: IntelliJ IDEA 2022.1.1 (Community Edition)
* Java: OpenJDK 11

**Comment by OlegFilippoff** [comment]
![image](https://user-images.githubusercontent.com/94902304/179732386-6c8a3388-30e4-4131-84bf-f8200d657c1a.png)
close #2
