### ISSUE TITLE
Не добавляется игровое время игроку в методе sumGenre 

### ISSUE THREAD

**Issue by VictoriaTatarinova** [OlegFilippoff/teamTask#3]
### Описание
Метод *public int sumGenre* не суммирует время игр, проигранное во все игры этого жанра этим игроком.

### Локация дефекта
https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/main/java/ru/netology/Player.java#L45-L55

### Шаги воспроизведения
1. Открыть [код программы](https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/main/java/ru/netology/Player.java) в IDEA.
2. Запустить [тест](https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/test/java/ru/netology/PlayerTest.java#L26)
*Ожидаемый результат*: На консоли выводится 5.
*Фактический результат*: На консоли выводится 0.

### Скриншот
<img width="1249" alt="Снимок экрана 2022-07-16 в 22 43 17" src="https://user-images.githubusercontent.com/103593418/179371351-751ec03f-3ffd-4345-93ff-a008a3751e85.png">

### Окружение
* Операционная система: macOS Monterey 12.3.1
* IDE: IntelliJ IDEA 2022.1.1 (Community Edition)
* Java: OpenJDK 11

**Comment by OlegFilippoff** [comment]
![image](https://user-images.githubusercontent.com/94902304/179734155-fd7e2d15-17f8-43b9-a984-cd825c1a7b6a.png)
fixed #3
