### ISSUE TITLE
Не выдается ошибка в методе play при отрицательном количестве часов 

### ISSUE THREAD

**Issue by VictoriaTatarinova** [OlegFilippoff/teamTask#4]
### Описание
При добавлении отрицательного значения в методе play не выдается ошибка *Exception*.

### Шаги воспроизведения
1. Открыть [код программы](https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/main/java/ru/netology/Player.java) в IDEA.
2. Запустить [тест](https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/test/java/ru/netology/PlayerTest.java#L102)

*Ожидаемый результат*: На консоли выводится ошибка.
*Фактический результат*: На консоли не выводится ошибка.

### Скриншот
<img width="1249" alt="Снимок экрана 2022-07-16 в 23 19 11" src="https://user-images.githubusercontent.com/103593418/179372237-95ccc49b-320e-41dc-a247-d15d116095aa.png">

### Окружение
* Операционная система: macOS Monterey 12.3.1
* IDE: IntelliJ IDEA 2022.1.1 (Community Edition)
* Java: OpenJDK 11

**Comment by VictoriaTatarinova** [comment]
### Локация дефекта
https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/main/java/ru/netology/Player.java#L33-L41

**Comment by OlegFilippoff** [comment]
![image](https://user-images.githubusercontent.com/94902304/179734405-d27f6a27-a073-46b4-9d3f-a3eb9f858b1f.png)
fixed #4
поправил ассерт с exeption.class на runtimeExeption.class
