### ISSUE TITLE
Метод mostPlayerByGenre не находит игру, в которую играют больше

### ISSUE THREAD

**Issue by VictoriaTatarinova** [OlegFilippoff/teamTask#5]
### Описание
Метод *mostPlayerByGenre* не находит игру в которую играли больше всего.

### Локация дефекта
https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/main/java/ru/netology/Player.java#L59-L61

### Шаги воспроизведения
1. Открыть [код программы](https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/main/java/ru/netology/Player.java) в IDEA.
2. Запустить [тест](https://github.com/OlegFilippoff/teamTask/blob/172344ff610bfe44ea2719f2447f7faed151ddd7/src/test/java/ru/netology/PlayerTest.java#L63)

*Ожидаемый результат*: На консоли выводится *Асассин крид*.
*Фактический результат*: На консоли выводится *null*.

### Скриншот
<img width="1249" alt="Снимок экрана 2022-07-16 в 23 45 27" src="https://user-images.githubusercontent.com/103593418/179372819-bf4ec040-313f-4e53-8ca6-9b29facea0a5.png">

### Окружение
* Операционная система: macOS Monterey 12.3.1
* IDE: IntelliJ IDEA 2022.1.1 (Community Edition)
* Java: OpenJDK 11

**Comment by OlegFilippoff** [comment]
![image](https://user-images.githubusercontent.com/94902304/179734821-bedaf02b-de0f-4b31-b9ba-73d3ae5b7bd1.png)
fixed #5
