### ISSUE TITLE
При работе метода containsGame условия в цикле не выполняются 

### ISSUE THREAD

**Issue by OlegFilippoff** [OlegFilippoff/teamTask#6]
**Описание**

счетчик в цикле всегда равен размеру коллекции из одного элемента, условие, при котором i меньше размера коллекции из одного элемента недостижимо.

**Локация дефекта**
https://github.com/OlegFilippoff/teamTask/blob/b2c29da3e4a5359fa5ad29a84eb73d27b79814e1/src/main/java/ru/netology/GameStore.java#L33
**Шаги воспроизведения**

1. Открыть [код программы](https://github.com/OlegFilippoff/teamTask/blob/master/src/main/java/ru/netology/GameStore.java#L33) в IDEA.

1. Запустить [тест](https://github.com/OlegFilippoff/teamTask/blob/092eed6c73d0c1482953a4444cbd3a04ddace121/src/test/java/ru/netology/GameStoreTest.java#L14-L23) shouldAddGame

Ожидаемый результат: метод проверяет наличие добавленной игры в коллекции, выводит true.
Фактический результат: В консоли выводится ошибка со значением false, что такой игры нет в каталоге.

**Скриншот**

![containsGame](https://user-images.githubusercontent.com/94902304/179390606-3fdccac6-f7c0-4df4-a732-e2d5467f0bd1.png)

**Окружение**
Операционная система: Windows 10 homeEditon
IDE: IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2034M
Cores: 8
Non-Bundled Plugins:
    com.javarush.plugin2 (3.57)
    Key Promoter X (2022.2)
Kotlin: 221-1.6.20-release-285-IJ5080.210
Java: OpenJDK 11

**Comment by VictoriaTatarinova** [comment]
![image](https://user-images.githubusercontent.com/103593418/179737057-0c6c1831-c5a9-4767-9a41-3065cb66a9f5.png)

fixed issue#6
