### ISSUE TITLE
метод getMostPlayer не определяем игрока с наибольшим временем игры, если время равно 1 час или менее.

### ISSUE THREAD

**Issue by OlegFilippoff** [OlegFilippoff/teamTask#7]
**Описание**
При запуске метода getMostPlayer сумма наигранных часов игроком (playerTime) изначально сравнивается с 1 часом (mostTime), и только в случае большего значения playerTime проходит условие. Корректнее сравнивать изначально с нулем, либо в условии сравнения поставить (больше или равно) mostTime, чтобы игрок с суммой часов в игру 1 час выводился в результат.

**Локация дефекта**
https://github.com/OlegFilippoff/teamTask/blob/092eed6c73d0c1482953a4444cbd3a04ddace121/src/main/java/ru/netology/GameStore.java#L58-L69
**Шаги воспроизведения**

1. Открыть [код программы](https://github.com/OlegFilippoff/teamTask/blob/gamestore/src/main/java/ru/netology/GameStore.java) в IDEA.

1. Запустить [тест](https://github.com/OlegFilippoff/teamTask/blob/42a9d0b64c32a9d5aa45d96a7a69cb6ccfa2e4d8/src/test/java/ru/netology/GameStoreTest.java#L65) shouldAddPlayerTimeOneHour

Ожидаемый результат: Возвращает значение "Bob"
Фактический результат: Возвращает NULL

**Скриншот**
![oneHourGameStoreTest](https://user-images.githubusercontent.com/94902304/179730020-5ba3f3db-d7ac-4f55-8519-74cad4a5769b.png)

**Окружение**
Операционная система: Windows 10 homeEditon
IDE: IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2034M
Cores: 8
Non-Bundled Plugins:
    com.javarush.plugin2 (3.57)
    Key Promoter X (2022.2)
Kotlin: 221-1.6.20-release-285-IJ5080.210
Java: OpenJDK 11

**Comment by VictoriaTatarinova** [comment]
![image](https://user-images.githubusercontent.com/103593418/179737441-42da81fd-4d8c-405a-86c8-03f5c1127119.png)

fixed issue#7
