### ISSUE TITLE
Метод addPlayTime не суммирует кол-во наигранных часов

### ISSUE THREAD

**Issue by OlegFilippoff** [OlegFilippoff/teamTask#8]
**Описание**
Метод addPlayTime перезаписывает при добавлении нового кол-ва времени (hours) зарегистрированному игроку, а не суммирует это значение с предыдущим кол-вом часов этого игрока. Следует к функции добавления времени по ключу добавить суммирование hours к текущему value.

**Локация дефекта**
https://github.com/OlegFilippoff/teamTask/blob/092eed6c73d0c1482953a4444cbd3a04ddace121/src/main/java/ru/netology/GameStore.java#L48
**Шаги воспроизведения**

1. Открыть [код программы](https://github.com/OlegFilippoff/teamTask/blob/092eed6c73d0c1482953a4444cbd3a04ddace121/src/main/java/ru/netology/GameStore.java#L46-L52) в IDEA.

1. Запустить [тест](https://github.com/OlegFilippoff/teamTask/blob/092eed6c73d0c1482953a4444cbd3a04ddace121/src/test/java/ru/netology/GameStoreTest.java#L82-L97) shouldAddPlayerTimeToTime

Ожидаемый результат: Возвращает значение наигранных часов игроками ("6")
Фактический результат: Возвращает последние значения hours по игрокам ("3")

**Скриншот**
![addTimeToTime](https://user-images.githubusercontent.com/94902304/179391937-f9d3e12f-e52e-4436-93ac-ef26cf0f04c8.png)

**Окружение**
Операционная система: Windows 10 homeEditon
IDE: IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2034M
Cores: 8
Non-Bundled Plugins:
    com.javarush.plugin2 (3.57)
    Key Promoter X (2022.2)
Kotlin: 221-1.6.20-release-285-IJ5080.210
Java: OpenJDK 11

**Comment by OlegFilippoff** [comment]
В ассерте учувствует метод getSumPlayedTime, который требует доработки для корректного получения актуального результата. Сейчас он по умолчанию возвращает 0.
Ссылка на описание https://github.com/OlegFilippoff/teamTask/issues/9

**Comment by VictoriaTatarinova** [comment]
![image](https://user-images.githubusercontent.com/103593418/179737718-3b53e341-f928-43cc-b64b-bbaa86f9aa0d.png)

fixed issue#8
