### ISSUE TITLE
метод getSumPlayedTime не считает кол-во наигранных часов по всем игрокам и всегда возвращает 0.

### ISSUE THREAD

**Issue by OlegFilippoff** [OlegFilippoff/teamTask#9]
**Описание**
Метод getSumPalyedTime не реализован, логика проверок и условий отсутствует
Следует вызвать значение value у каждого игрока по имени, и сложить все значения value в отдельную переменную. Вернуть значение этой переменной.

**Локация дефекта**
https://github.com/OlegFilippoff/teamTask/blob/b2c29da3e4a5359fa5ad29a84eb73d27b79814e1/src/main/java/ru/netology/GameStore.java#L75-L77
**Шаги воспроизведения**

1. Открыть [код ](https://github.com/OlegFilippoff/teamTask/blob/092eed6c73d0c1482953a4444cbd3a04ddace121/src/main/java/ru/netology/GameStore.java#L46-L52) в IDEA.

1. Запустить [тест ](https://github.com/OlegFilippoff/teamTask/blob/5f137dad4b7403b57bee668c81e4b42063857872/src/test/java/ru/netology/GameStoreTest.java#L51)shouldReturnAllPlayedTimeSum

Ожидаемый результат: Возвращает значение наигранных часов (8)
Фактический результат: Возвращает значение (0)

**Скриншот**
![PalyedTimeSum](https://user-images.githubusercontent.com/94902304/179392850-9e6787f5-8647-43e8-9375-e6420ed03297.png)

**Окружение**
Операционная система: Windows 10 homeEditon
IDE: IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2034M
Cores: 8
Non-Bundled Plugins:
    com.javarush.plugin2 (3.57)
    Key Promoter X (2022.2)
Kotlin: 221-1.6.20-release-285-IJ5080.210
Java: OpenJDK 11

**Comment by VictoriaTatarinova** [comment]
![image](https://user-images.githubusercontent.com/103593418/179737939-b5520311-fbfa-46fa-8f8e-61ce901c5536.png)

fixed issue#9
